spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_clone
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/whatsapp-clone
  # Audio - Video settings
  servlet:
    multipart:
      max-file-size: 50MB

# Path in route folder for uploads
application:
  files:
    uploads:
      media-output-path: ./uploads